FROM alpine:3.16.2 as builder

WORKDIR /opt/

RUN apk add curl protoc musl-dev gzip git

# shello-container
RUN curl -sLO https://github.com/horowitzathome/hello-container/releases/latest/download/hello-container-aarch64-apple-darwin.tar.gz \
  && tar -xvf hello-container-aarch64-apple-darwin.tar.gz \
  && chmod +x hello-container

############# Now create the image ##############

# FROM gcr.io/distroless/static:nonroot-arm
FROM arm64v8/ubuntu:latest

WORKDIR /opt

# Copy our build
COPY --from=builder /opt/hello-container /usr/local/bin/
EXPOSE 8081
CMD ["hello-container"]