name: "Check and Test"

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always    

jobs:
  check-test:
    name: "Cargo check"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: "Check code"
        run: cargo check --verbose

      - name: "Test code"
        run: cargo test --verbose  
        
      - name: "Check if well formatted"
        run: cargo fmt --all -- --check  